import Link from 'next/link';
import { FiMap, FiDollarSign, FiCalendar, FiTrendingUp } from 'react-icons/fi';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 via-white to-primary-50">
      {/* Header */}
      <header className="container mx-auto px-4 py-6">
        <nav className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <FiMap className="text-primary-600 text-3xl" />
            <span className="text-2xl font-bold text-gray-900">AI Travel Planner</span>
          </div>
          <div className="space-x-4">
            <Link
              href="/auth/login"
              className="text-gray-700 hover:text-primary-600 font-medium"
            >
              Login
            </Link>
            <Link
              href="/auth/signup"
              className="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700 transition-colors font-medium"
            >
              Sign Up
            </Link>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="text-center max-w-4xl mx-auto">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6 animate-fade-in">
            Plan Your Dream Trip with{' '}
            <span className="text-primary-600">AI Power</span>
          </h1>
          <p className="text-xl text-gray-600 mb-8 animate-fade-in">
            Get personalized itineraries tailored to your budget, interests, and travel style.
            Let AI handle the planning while you focus on the adventure.
          </p>
          <Link
            href="/auth/signup"
            className="inline-block bg-primary-600 text-white px-8 py-4 rounded-lg text-lg font-semibold hover:bg-primary-700 transition-colors shadow-lg hover:shadow-xl animate-slide-up"
          >
            Start Planning for Free
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <FeatureCard
            icon={<FiMap className="text-4xl" />}
            title="AI-Powered Itineraries"
            description="Get detailed day-by-day plans generated by advanced AI based on your preferences"
          />
          <FeatureCard
            icon={<FiDollarSign className="text-4xl" />}
            title="Budget Optimization"
            description="Stay within your budget with accurate cost estimates for each activity"
          />
          <FeatureCard
            icon={<FiCalendar className="text-4xl" />}
            title="Flexible Planning"
            description="Customize trip duration, destinations, and activities to match your schedule"
          />
          <FeatureCard
            icon={<FiTrendingUp className="text-4xl" />}
            title="Smart Analytics"
            description="Track your travel history and spending with insightful dashboards"
          />
        </div>
      </section>

      {/* How It Works */}
      <section className="container mx-auto px-4 py-20 bg-white/50 rounded-3xl my-10">
        <h2 className="text-4xl font-bold text-center text-gray-900 mb-12">
          How It Works
        </h2>
        <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          <Step
            number="1"
            title="Enter Your Details"
            description="Tell us your destination, budget, travel days, and interests"
          />
          <Step
            number="2"
            title="AI Generates Your Plan"
            description="Our AI creates a personalized itinerary with activities and costs"
          />
          <Step
            number="3"
            title="Save & Track"
            description="Save your trips, regenerate plans, and track your travel history"
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-4 py-20 text-center">
        <div className="bg-gradient-to-r from-primary-600 to-primary-700 rounded-3xl p-12 shadow-2xl">
          <h2 className="text-4xl font-bold text-white mb-4">
            Ready to Start Your Adventure?
          </h2>
          <p className="text-primary-100 text-lg mb-8">
            Join thousands of travelers who trust AI to plan their perfect trips
          </p>
          <Link
            href="/auth/signup"
            className="inline-block bg-white text-primary-600 px-8 py-4 rounded-lg text-lg font-semibold hover:bg-primary-50 transition-colors shadow-lg"
          >
            Create Your Free Account
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="container mx-auto px-4 py-8 text-center text-gray-600">
        <p>&copy; 2024 AI Travel Planner. Built with Next.js, OpenAI, and Supabase.</p>
      </footer>
    </div>
  );
}

function FeatureCard({
  icon,
  title,
  description,
}: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
      <div className="text-primary-600 mb-4">{icon}</div>
      <h3 className="text-xl font-bold text-gray-900 mb-2">{title}</h3>
      <p className="text-gray-600">{description}</p>
    </div>
  );
}

function Step({
  number,
  title,
  description,
}: {
  number: string;
  title: string;
  description: string;
}) {
  return (
    <div className="text-center">
      <div className="w-16 h-16 bg-primary-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">
        {number}
      </div>
      <h3 className="text-xl font-bold text-gray-900 mb-2">{title}</h3>
      <p className="text-gray-600">{description}</p>
    </div>
  );
}
